CREATE TABLE IF NOT EXISTS orders (
  id SERIAL PRIMARY KEY,
  userId INTEGER NOT NULL,
  products TEXT[] NOT NULL,
  total DOUBLE PRECISION NOT NULL,
  status VARCHAR(100) NOT NULL,
  createdAt TIMESTAMP NOT NULL
);
